name: learnio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.1
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  flutter_calendar_carousel: ^2.4.2
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


assets:
    - assets/images/

fonts:
    - family: Red Hat Display
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/RedHatDisplay-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/RedHatDisplay-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-MediumItalic.ttf
          style: italic
          weight: 600
    - family: BoxIcons
      fonts:
        - asset: assets/fonts/BoxIcons.ttf